travis:
  secure:
    BINSTAR_TOKEN: zFq60uk7H3irTnVSlmJbxe/TtFCZqrS/HMOwArJEy3xWXJWDNL9Uqrq0wj3mblu6MXoOAC+iX6pKAcP9WiadnQskLxndzVaDMA4cvfkpEYyRaKPLElmowPykBL0kwIYRbg95qNHpJDBhsDOSZgtKsTrJTxSl/NSGuWslXXWkqvxQNlko4QmDFRSQ2RbYIbIOtYUlthZnXDCM0ywf0P6d41ZgCc3zSkkAk8q5xzbytSRVAzVha0msLA7H5hu38cwIvPUbnG0rBx5xFvg+9Wqp56y3DzerDXWgz7J4oq7EysaXYBeavt0ghBIQb5DIY+YRuEvNfE8y7dVZH7YJvrEh0doYJ+Mt/p6CQipQEq4UcMjtlxawvZcTYvspw9YlLU1V17CvK05mtUZOG4QK9RSKOYFm9Ly8fwn2InMkB7yqt60wQCW/IExfeEBa9rRaD8J5ldHECDxl2lzbtb6KqndHI3elfTDrnDhuiOjEQKu+MTwVWgXp6wmnGG2/UZzUwh0y5aHGBHfNlHZlYUnt+8EfKlICw3hFnVho8jLXQYnF72FU6IxxfXkOy+4bcxxopDs0f6WeNtc9DaH7kuKWnhTAie8nPYg8vN78t4VBdtszaEoK2z7nA1IHzO9owtO6dMmgjvqFGEqbxlKTVeM0UAZjRa7LJRyzFUF1j6KE3e/bmJs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
